AT_BANNER([LIXA recovery failed clean-up (bug 2983464)])

AT_SETUP([Preparing failed transaction])
AT_DATA([monkey1s.conf],
[[# first monkey R.M. config
xa_open/0
xa_start/0
xa_end/0
xa_prepare/0
xa_commit/0
xa_close/0
]])
AT_DATA([monkey2s.conf],
[[# second monkey R.M. config
xa_open/0
xa_start/0
xa_end/0
xa_prepare/0
xa_commit/0
xa_close/0
]])
AT_DATA([monkey3s.conf],
[[# third monkey R.M. config
xa_open/0
xa_start/0
xa_end/0
xa_prepare/0
xa_commit/0
xa_close/0
]])
AT_CHECK([export LIXA_PROFILE=CASE_PROF_0000 ; export LIXA_CRASH_POINT=1 ; lixa_test_exec.sh reset start case0000], [134], [ignore], [ignore])
AT_CLEANUP

AT_SETUP([Recovering failed transaction])
AT_DATA([monkey1s.conf],
[[# first monkey R.M. config
xa_open/0
xa_commit/0
xa_start/0
xa_end/0
xa_prepare/0
xa_commit/0
xa_close/0
]])
AT_DATA([monkey2s.conf],
[[# second monkey R.M. config
xa_open/0
xa_commit/0
xa_start/0
xa_end/0
xa_prepare/0
xa_commit/0
xa_close/0
]])
AT_DATA([monkey3s.conf],
[[# third monkey R.M. config
xa_open/0
xa_commit/0
xa_start/0
xa_end/0
xa_prepare/0
xa_commit/0
xa_close/0
]])
AT_CHECK([export LIXA_PROFILE=CASE_PROF_0000 ; lixa_test_exec.sh noreset stop case0000], [0], [ignore], [ignore])
AT_CLEANUP

